idf_component_register(
    SRCS
        "src/bsp_aux.c"
        "src/bsp_bluetooth.c"
        "src/bsp_board.c"
        "src/bsp_ch376.c"
        "src/bsp_input.c"
        "src/bsp_mode.c"
        "src/bsp_oled.c"
        "src/bsp_speaker.c"
        "src/bsp_sd.c"
        "src/bsp_usb_player.c"
    INCLUDE_DIRS "include"
    REQUIRES
        esp_hw_support
        spi_flash
        log
        driver
        fatfs
        sdmmc
        esp_driver_spi
        esp_driver_sdspi
        esp_driver_i2s
        bt
        nvs_flash
)
